name: Playwright CI Multi-Env

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [qa, uat, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (${{ matrix.env }})
        env:
          ENV: ${{ matrix.env }}
        run: npx playwright test

      - name: Upload Report (${{ matrix.env }})
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.env }}
          path: playwright-report/